/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("apktool.kotlin.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("org.jetbrains.kotlinx:kotlinx-cli:0.3.6")
    implementation(project(":lib"))
}

application {
    // Define the main class for the application.
    mainClass.set("apktool.kotlin.app.AppKt")
}
