/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package apktool.kotlin.app


import apktool.kotlin.lib.Apktool
import java.io.File
import java.nio.file.Path
import java.nio.file.Paths

fun main(args: Array<String>) {


    Apktool(
            apkFile = args[0],
            decodeResource = false,
            cleanDecompilationFolder = false
    ).use {
        val decompiledFiles: Array<File> = it.decompilationFolder!!.toFile().listFiles()!!

        for (f: File in decompiledFiles) {
            println("${f.absolutePath}")
        }
        // ============== begin the patch process ================
        val apiFolderPath = File(it.decompilationFolder.toString(), "smali/com/android/billingclient/api/")
        val billingClientFiles: Array<File> = apiFolderPath.listFiles()

        // for folder, find the exact and replace
        for (f in billingClientFiles) {
            // write
            val text: String = f.readText()
            val newPackageToOverwrite = "\"com.kuhakupixel.purchaseserver\""
            println("writting to ${f.absolutePath}")
            text.replace("\"com.android.vending\"", newPackageToOverwrite)
            text.replace("\"com.android.vending.billing.InAppBillingService.BIND\"", newPackageToOverwrite)
        }


        it.export("Recompiled.apk", signApk = true)
    }


}
