/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package apktool.kotlin.app


import apktool.kotlin.lib.Apktool

fun main(args: Array<String>) {


    Apktool(
            apkFile = args[0],
            decodeResource = false,
            cleanDecompilationFolder = true
    ).use {
        it.export("Recompiled.apk")
    }


}
